#[repr(C, packed)]
pub struct Ammo {
    pub reticle: u64,
    pub item_name: [u8; 32],
    pub shell_kind: [char; 32],
    pub shell_kind2: [char; 32],
    pub milimeterage: [char; 32],
    pub shell_name: [char; 32],
    pub sign_ammo: [char; 32],
    pub unknown_cch: f32,
    pub padding: u32,
    pub shell_in: [char; 32],
    pub shell_out: [char; 32],
    pub shell_far: [char; 32],
    pub caliber: u32,
    pub index: u32,
    pub speed: f32,
    pub ap_drag: f32,
    pub explosive_power: f32,
    pub penetrative_power: f32,
    pub incendiary_power: f32,
    pub incendiary_14ch: u32,
    pub incendiary_150h: f32,
    pub incendiary_154h: f32,
    pub unknown_158h: f32,
    pub unknown_15ch: u32,
    pub unknown_160h: f32,
    pub unknown_164h: u32,
}
